#!/usr/bin/python

import os
import sys
import time
import argparse

command = ""
delay = 60
executions = 0
i = 0

try:

	if len(sys.argv) < 2:
		command = input('Command: ')
		if command == '':
			sys.exit('error: you need to provide a command')
		try:
			idelay = input('Delay (default 60 seconds): ')
			if idelay != '':
				delay = float(idelay)
			iexecutions= input('Number of executions (default infinite): ')
			if iexecutions != '':
				executions = int(float((iexecutions)))
		except:
			sys.exit('error: wrong arguments')
	else:
		parser = argparse.ArgumentParser()
		parser.add_argument('command', type=str)
		parser.add_argument('-d', help='Delay in seconds')
		parser.add_argument('-n', help='Number of executions')
		args = parser.parse_args()

		try:
			if args.command != None:
				command = str(args.command)
			if args.d != None:
				delay = float(args.d)
			if args.n != None:
				executions = int(args.n)
		except:
			sys.exit('error: wrong arguments')


	while True:
		os.system(command)
		if executions: 
			i += 1
			if i >= executions:
				break
		time.sleep(delay)
		print()

except KeyboardInterrupt:
	print()
	pass